### PR TITLE
Add flake8-import-order

### PR DESCRIPTION
**Pull request by majorgreys**

### CODE REVIEW

**Comment by Kyle-Verhoog** [comment]
@majorgreys is there an autoformatter for these? I vaguely recall you mentioning one before.

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by majorgreys** [comment]
> @majorgreys is there an autoformatter for these? I vaguely recall you mentioning one before.

Right, https://pypi.org/project/isort/ would give us an automatic way to check imports. Being we have a small codebase at this point, I opted to first try the `flake8-import-order`.

**Comment by Kyle-Verhoog** [comment]
cool, makes sense to me!

**Comment by jd** [comment]
Yeah I was going to propose `isort`, it's easier to use :)

**Pull request merged**
